### ISSUE TITLE
Main Not found in trustframework

### ISSUE THREAD

**Issue by francesco-giannico** [Tulivick/ARSENAL_GSD#1]
After I tried to run with the command: java -jar "ArsenalGSD.jar", it isn't able to find the main class in trustframework. 

Inspecting the class trustframework, I discover that the main is not defined.

**Comment by Tulivick** [comment]
@frankgiak, you are right, there is no main defined in ArsenalGSD.jar. 

The right command is: java -jar Arsenal_GSD_GUI.jar.

**Comment by frankgiak** [comment]
ok, thank you! #close

**Comment by francesco-giannico** [comment]
ok thank you!
